### ISSUE TITLE
Add Additional Overlay Layers to Layer Selector

### ISSUE THREAD

**Issue by msilski** [agrc/wfrc-rtp-projects#109]
We just received a request to include toggles for additional layers in the web app (here is our [latest production version](https://wfrc.org/rtp-2023-workshops-map/)). These layers (existing bus routes, group layer showing UTA's 5 year transit service plan, possibly additional layers) would draw on top of the main transportation project layers. I will include the layers in the same [web map](https://wfrc.maps.arcgis.com/apps/mapviewer/index.html?webmap=b815b099890642218f69bb7647274f87) as the transportation project layers.

I'm envisioning that toggles for these additional layers would go in the Layer Selector widget in the same section as Overlay and Cities:

![image](https://user-images.githubusercontent.com/1699870/196994435-8a1f7f5e-05fc-46be-92f9-c6622a019342.png)

I received this request this morning from our planning group and they are asking for it to be ready by November 3rd/4th in time for a workshop on Monday, November 7th. Would it be possible for you to help me implement this in the web app? If it resides within the Layer Selector widget, I hope it won't be too difficult to do. Let me know what you think.

**Comment by stdavis** [comment]
<img width="451" alt="image" src="https://user-images.githubusercontent.com/1326248/197630509-7eb8fb47-4ad9-48fa-ae14-cfdcdbaf7fe4.png">
