### ISSUE TITLE
URL Parameterization

### ISSUE THREAD

**Issue by bert-granberg** [agrc/wfrc-rtp-projects#13]
Let's talk about the feasibility for the following URL parameters when it makes sense...

- [x] Map Scale and Center
- [x] Project Filter UI State
- [x] Selected Project

**Comment by stdavis** [comment]
>We would still like to use URL parameters on this map. The map scale and center parameters would be really nice to have so we can share zoomed-in views/URLs of the map. It might be nice to have URL parameters that show combinations of transportation modes and combinations of phases, but this might get complicated.
