### ISSUE TITLE
WFRC RTP - Weird Project Search Error

### ISSUE THREAD

**Issue by bert-granberg** [agrc/wfrc-rtp-projects#221]
If I look two projects  R-W-52 from project R-S-119 separately the Sherlock search tool works great. But if search for the first one in sherlock search window, then expand the project information results box, then search for the second project in the sherlock window, the app crashes. This happens for other sequential uses of the Sherlock tool, but certainly not all. This is **_low priority_** but it would be good to assess the problem and get a sense for the scale of any fix. 

Error message looks like this:

Error!
Looks like something went wrong.

Cannot read properties of null (reading 'id')

**Comment by nathankota** [comment]
Tested and validated on https://wfrc-rtp.dev.utah.gov/
- entered R-W-52 in search, and clicked to zoom to it
- entered R-S-119 in search, and clicked to zoom to it
- entered R-W-52 in search, and clicked to zoom to it
- clicked on feature to populate Project Information
- expanded project info
- entered R-S-119 in search, clicked on it in the drop down to zoom to project
- clicked on project information to expand
- repeated with multiple other projects
