### ISSUE TITLE
Handle Verticle Scrolling

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc-rtp-projects#28]
The filter box does not handle verticle scrolling well. Need to add a max height and scrollbar.

![Image](https://user-images.githubusercontent.com/1326248/173954979-f32a0cfc-05eb-4b16-8198-8c5b062ae86b.png)

**Comment by nathankota** [comment]
Implemented in [WFRC's test app](https://wfrc.org/testing/wfrc-rtp-projects/), and looks great.
