### ISSUE TITLE
UX Improvements for Cost Filter

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc-rtp-projects#32]
From Matthew:
>Sounds good. I like adding commas to the input box to help make larger numbers more clear. That form section could also be retitled from "Filter By Project Cost (in millions, 2023 dollars):" to "Filter By Project Cost (in 2023 dollars):".

- [x] automatically add commas to the input boxes
- [x] update header to be "Filter By Project Cost (in 2023 dollars):"

**Comment by steveoh** [comment]
Would it be an improvement for the bundle size to use [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) since it's built in and localized etc?

**Comment by stdavis** [comment]
`.toLocalString()` on the number also adds commas but it loses the cursor position if you edit any but the last character. After looking into the code for working around that issue, I decided that the react-number-format library was a better option.
