### ISSUE TITLE
More Dynamic Layout

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc-rtp-projects#44]
Feedback from Matthew
>Having the half-size Filter widget and half-size Project Information widget makes the interface nice and compact, but it condenses the Filter widget so that it's difficult to view the Advanced filter when it's toggled. Would there be a way for the user to expand the half-size Filter to make it full-size?
I understand this would interfere with the Project Information widget. Would it make sense to move the Project Information filter to the bottom left of the screen? I'm open to other creative solutions.
If the Filter widget will work best as-is (half-size), could we add a "Scroll to Top" toggle/button that will help orient the user?

There are definitely some awkward layouts:

Wasted space
![Image](https://user-images.githubusercontent.com/1326248/178832196-bfe2d606-d895-46fc-9acf-db083b818501.png)

Lots of scrolling
![Image](https://user-images.githubusercontent.com/1326248/178832302-48950023-5d49-4f65-8810-f17a5e617c13.png)

An idea from our last meeting was to add a draggable handle to the space between the two widgets that a user could use to dynamically change the sizes of the widgets. As one gets bigger, the other would get smaller.

Other improvements that were discussed:
- [x] when only one widget is open, it should expand to take up the entire verticle space
- [x] when the advanced filter is closed, it should auto-scroll to make sure that the simple filter is in view

**Comment by msilski** [comment]
I really like the solution for this issue. It's nice that the user can show the Filter widget full-size or the Project Info widget full-size or show both half-size widgets.

**Comment by msilski** [comment]
I'll go ahead and deploy the most recent release that includes this dynamic layout solution. I think this should resolve this issue unless there are other layout-related tasks that you can remember.
