### ISSUE TITLE
Auto-toggle Primary Checkboxes

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc-rtp-projects#46]
>Unchecking all the mode section's checkboxes turns on all the mode's data on the map. It should turn off the mode's map data _and turn off the main, primary checkbox at the top_.

The UX starts to get funky once you start treating the primary checkbox as a select all/unselect all. For example, if you turn off all of the project types for a specific mode and its primary checkbox is automatically unchecked, what would you expect to happen when the user toggles the primary checkbox back on? Turn on all of the project type checkboxes? Then what about when you toggle it off?

I would argue that it's best to keep it as is. The primary checkbox toggles the disabled state of the secondary ones.

But, of course, I'm open to other ideas and you guys are the ones that make the final decision.

**Comment by msilski** [comment]
Bert and I talked through this one. We agree - let's keep the various filter checkboxes the way they currently select all/unselect all as-is.
