### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc-rtp-projects#65]
>We would also like to add a simple splash screen to the map similar to Web AppBuilder's Splash widget. Ideally, the splash screen would take HTML input that we could create in the config file. It would be nice if there was an option in the config file to enable or disable the splash screen. It might also be nice to have a "Don't Show This Again" checkbox for users to dismiss the splash screen for future sessions. The use case: when we disable commenting on this map, the splash screen would inform users that commenting is no longer permitted on the map. It could also serve the purpose of a simple info panel ([issue #43](https://github.com/agrc/wfrc-rtp-projects/issues/43)).

**Comment by stdavis** [comment]
Another thought: As currently implemented, once the user checks the "Don't Show This Again" option, then the splash screen will never be shown to that user again unless they manually clear their browser's localStorage or maybe after a major browser upgrade or something.

We could make it so that this is specific to the version of the application. So each time the app version number changes, the user would have to dismiss it again.

**Comment by msilski** [comment]
I tested out the splashScreen.enabled property and I'm not sure it is working. I've set it to false, set it to null, and removed the property from the config and the splashScreen stays enabled. Could you take a look at it?
