### ISSUE TITLE
Facilities type limits

### ISSUE THREAD

**Issue by nathankota** [agrc/wfrc-rtp-projects#70]
> There is currently a "Limit to UDOT Facilities" button for the Road and Active Transportation project types. 
> 
> I believe this draws upon a single attribute that is binary...each project is either attributed as a UDOT road or Local facility
> 
> Our long range planning staff would like to have the current 'Limit to UDOT Facilities' option and an option to 'Limit to Local Facilities.
> 
> This could possible be done similarly to what I had mocked up yesterday for the Limit to Needs [<|=] FC enhancement, wherein in this additional enhancement, there is, similarly, a check box to enable Limit to [UDOT|Local] Facilities with a hover for info/click to toggle between the two options.

**Comment by stdavis** [comment]
@bgranberg or @msilski:
Would these queries work for this new control?

Limit to UDOT Facilities: `lower(breakout) LIKE '%udot%'`
Limit to local Facilities: `lower(breakout) LIKE '%local%'`

These, of course, would be configurable. I'm thinking that the config would look something like this:

```json
"Limit to {option} Facilities": {
  "field": "breakout",
  "labels": ["UDOT", "local"],
  "values": ["udot", "local"],
  "offByDefault": true,
  "useAnd": true
}
```

**Comment by msilski** [comment]
The issue with this is that the attributes for the breakout column for the Roadway and Active Transportation project types can be State, Local, or State/Local. I'm not sure how to resolve this last, mixed category.

I _think_ the desired behavior would be for the Limit to UDOT Facilities control to show State AND State/Local; the Limit to Local Facilities control would show Local AND State/Local.

Limit to UDOT Facilities: lower(breakout) LIKE '%state%'
Limit to Local Facilities: lower(breakout) LIKE '%local%'

So the two controls would not be mutually exclusive. Would that work?

**Comment by stdavis** [comment]
Yes, that looks great. I got `udot` mixed up with `state` in my example queries. I'm working on this currently...
