### ISSUE TITLE
UDOT/Local Owned Restriction

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc-rtp-projects#8]
From mockups:
>On both panels, turning off both UDOT and Local owned facility check boxes together would not be allowed…a warning would be issued and they would both be turned back on

Blocked by #6

**Comment by stdavis** [comment]
@msilski / @bgranberg: What should the warning say? Why is it a problem that the user has turned off both UDOT and Local owned?

**Comment by msilski** [comment]
This is tricky. I'm thinking that the UDOT Owned Facility, Local Owned Facility, and Mixed Ownership types should be in a different/new filter section. They aren't mutually exclusive with the other project types (ex. a project can be Locally Owned and Operational, a project can be UDOT Owned and Interchange).

@bert-granberg do you think this widget can or should have a Filter By Ownership section? Perhaps with these options:

- UDOT
- UTA
- Local
- Mixed

**Comment by msilski** [comment]
Bert and I discussed this and we have a solution to recommend. I will update the mockup and key to the controls.
