### ISSUE TITLE
Make Configurable

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc-rtp-projects#9]
I remember that they wanted this app to be configurable but I don't remember the specifics and I don't have any related notes. @nathankota What do you remember? Also, were they going to push this to the Wasatch Choice map at some point in the future? This would play into what type of configuration scheme we use.

Note to self: don't forget to use `jsonschema` to validate the config file in a similar manner to the wasatch choice app.

**Comment by nathankota** [comment]
The configurability aspect was related to potential future implementation with other project datasets.

> ...there are potentially other project datasets for which this framework could be applied so we'll want to keep reuse in mind as well. 

And, yes, there was some interest in Wasatch Choice map integration.

> ...implement this as a standalone web app and potentially integration ideas for if/how the functionality could be made available in the Wasatch Choice map

**Comment by stdavis** [comment]
Feedback from Matthew:
>In the Wasatch Choice Map, text for each map tab is very configurable - layer names, phase values, map text, colors, etc. I like being able to control as much as I can in an app, especially where the code has been minified. I know the config.json for the Wasatch Choice Map was about 1500 lines, but I don't mind the tradeoff for the long config file for added flexibility. If it creates excessive work for you to build another long config file, maybe we could limit configuration to map layer names and check box queries.
